version: '2'

services:
  node_base:
    image: node:10.16.3-alpine
    volumes:
      - ${PWD}:/snowdays-front-end
    working_dir: /snowdays-front-end

  node_install:
    extends:
      service: node_base
    command: npm install

  webserver:
    extends:
      service: node_base
    command: npm start
    ports:
      - 8088:3000
