version: '2'

services:
  node_base:
    image: node:10.16.3-alpine
    volumes:
      - ${PWD}:/snowdays-front-end
    working_dir: /snowdays-front-end

  node_install:
    extends:
      service: node_base
    command: /bin/sh docker_dev_node_install.sh

  ## development use, watches scss and launches react in dev
  webserver:
    extends:
      service: node_base
    command: npm run forest
    env_file: .env.frontend
    ports:
      - 8088:3000 ##port on your network:port on docker network
    container_name: webserver
